const LANGUAGES: Record<string, string> = {
  en: "English",
  tl: "Tagalog",
  fil: "Filipino",
  tr: "Turkish",
  zh: "Chinese",
  sv: "Swedish",
  es: "Spanish",
  ro: "Romanian",
  pt: "Portuguese",
  pl: "Polish",
  nb: "Norwegian",
  ko: "Korean",
  ja: "Japanese",
  it: "Italian",
  hu: "Hungarian",
  el: "Greek",
  de: "German",
  fr: "French",
  fi: "Finnish",
  nl: "Dutch",
  da: "Danish",
  cs: "Czech",
  ru: "Russian",
  ar: "Arabic",
  he: "Hebrew",
  hi: "Hindi",
  vi: "Vietnamese",
  th: "Thai",
  id: "Indonesian",
  ms: "Malay",
  uk: "Ukrainian",
  sr: "Serbian",
  hr: "Croatian",
  sk: "Slovak",
  sl: "Slovenian",
  bg: "Bulgarian",
  lt: "Lithuanian",
  lv: "Latvian",
  et: "Estonian",
  ca: "Catalan",
  eu: "Basque",
  gl: "Galician",
  mt: "Maltese",
  is: "Icelandic",
  ga: "Irish",
  cy: "Welsh",
  mk: "Macedonian",
  bs: "Bosnian",
  sq: "Albanian",
  fo: "Faroese",
  ne: "Nepali",
  mn: "Mongolian",
};

export const getLanguageFullName = (code: string) =>
  LANGUAGES[code.toLowerCase()] || code;
